[[
	{'title': '기준금리 인상! 실생활에 미치는 영향?! | 행복한 아침 675 회',
   'movie': 'https://i.ytimg.com/an_webp/pK50AjJJvzA/mqdefault_6s.webp?du=3000&sqp=CIC2958G&rs=AOn4CLDVGh6IT2lxnIuYLVsXVMw-AQqz_A',
   'img': 'https://i.ytimg.com/vi/pK50AjJJvzA/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFTyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA9xatrDyD1Ai2OU7dI9qV9eg8b0w',
   'duration': '4:32', 'url': 'https://www.youtube.com/watch?v=pK50AjJJvzA', 'rdate': '1 year ago', 'cnt': '9,764 views'},
  {
	  'title': '기준금리 인상? 세상 쉽게 알려드림 #shorts', 'movie': 'https://i.ytimg.com/an_webp/7OgGCvkXH9o/mqdefault_6s.webp?du=3000&sqp=CJKL958G&rs=AOn4CLCeL-2whIEONSPTclbxyxY_yAqrqw',
   'img': 'https://i.ytimg.com/vi/7OgGCvkXH9o/hq720_2.jpg?sqp=-oaymwE2COgCEMoBSFTyq4qpAygIARUAAIhCGABwAcABBvABAfgBlAOAAtAFigIMCAAQARhlIFooVDAP&rs=AOn4CLBml_tzsUI4s2wyZ8XxdDTPZlZ2DQ',
   'duration': '1:00', 'url': 'https://www.youtube.com/watch?v=7OgGCvkXH9o', 'rdate': '7 months ago', 'cnt': '42,063 views'
   }
],
	[{'title': '美 금리 인상이 한국 경제에 미칠 영향은? [이슈분석]', 'movie': 'https://i.ytimg.com/an_webp/Do8HRxT5VxI/mqdefault_6s.webp?du=3000&sqp=CKis958G&rs=AOn4CLDkwzkXVacg1Ql8B8hvkYmwmp0pBw', 'img': 'https://i.ytimg.com/vi/Do8HRxT5VxI/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFTyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDAH1y0dfdTRabBmlLWug0Z8WMgyA', 'duration': '7:04', 'url': 'https://www.youtube.com/watch?v=Do8HRxT5VxI', 'rdate': '3 months ago', 'cnt': '23,585 views'}, {'title': '[1타강사] 물가 잡으려다 경제 잡는다?...기준금리 인상의 명암 / YTN', 'movie': 'https://i.ytimg.com/an_webp/J1TyBb_ltUI/mqdefault_6s.webp?du=3000&sqp=CPqk958G&rs=AOn4CLBju-dM36cqPVmygMkIqo5hLwd3xg', 'img': 'https://i.ytimg.com/vi/J1TyBb_ltUI/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFTyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUgWsv2sDvTYXLoQZ3W4wH3U1LBQ', 'duration': '1:42', 'url': 'https://www.youtube.com/watch?v=J1TyBb_ltUI', 'rdate': '7 months ago', 'cnt': '8,473 views'}], [{'title': '[1타강사] 물가 잡으려다 경제 잡는다?...기준금리 인상의 명암 / YTN', 'movie': 'https://i.ytimg.com/an_webp/J1TyBb_ltUI/mqdefault_6s.webp?du=3000&sqp=CPqk958G&rs=AOn4CLBju-dM36cqPVmygMkIqo5hLwd3xg', 'img': 'https://i.ytimg.com/vi/J1TyBb_ltUI/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFTyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUgWsv2sDvTYXLoQZ3W4wH3U1LBQ', 'duration': '1:42', 'url': 'https://www.youtube.com/watch?v=J1TyBb_ltUI', 'rdate': '7 months ago', 'cnt': '8,473 views'}, {'title': '미국 3연속 0.75%p 금리 인상…우리 경제 영향은? / JTBC 아침&', 'movie': 'https://i.ytimg.com/an_webp/vWjMtTXWaPU/mqdefault_6s.webp?du=3000&sqp=CNav958G&rs=AOn4CLANxYFUI5JKd1t4jdYGG7oJbnPFmg', 'img': 'https://i.ytimg.com/vi/vWjMtTXWaPU/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFTyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAk5jDAppFDB_Tosj7uC3ibmsFVQg', 'duration': '6:55', 'url': 'https://www.youtube.com/watch?v=vWjMtTXWaPU', 'rdate': '5 months ago', 'cnt': '19,110 views'}, {'title': '미국금리 인상하면 한국금리는 얼마나 오를까? (feat. 돈되는 7분 영상)', 'movie': 'https://i.ytimg.com/an_webp/iTP9sk6VvBc/mqdefault_6s.webp?du=3000&sqp=CKGl958G&rs=AOn4CLC5RAj6ZNoyhYfv6RsI5uQdwbb1Dw', 'img': 'https://i.ytimg.com/vi/iTP9sk6VvBc/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFTyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDkjZFg9jEhApcMiDj5ENMzOElbdA', 'duration': '4:53', 'url': 'https://www.youtube.com/watch?v=iTP9sk6VvBc', 'rdate': '7 months ago', 'cnt': '6,125 views'}]]